### ISSUE TITLE
Doesn't work on Firefox

### ISSUE THREAD

**Issue by JGotinha** [antiboredom/p5.gif.js#1]
The example runs fine on Chrome but it shows the following error on Firefox*:
"InvalidStateError: An attempt was made to use an object that is not, or is no longer, usable p5.min.js:6:0"

Here is the example online: https://cdn.rawgit.com/antiboredom/p5.gif.js/master/examples/index.html

*I'm using Firefox 43.0.4 on Ubuntu 14.04.

**Comment by bigrig2212** [comment]
Me too. Same error.

**Comment by bananlabs** [comment]
I have the same problem.. firefox doesn't work :(

**Comment by ztzven** [comment]
+1
