### ISSUE TITLE
Image(gif,w,h); does not work anymore?

### ISSUE THREAD

**Issue by Tuangping** [antiboredom/p5.gif.js#5]
Hi, your library worked great and I'm thankful for your work. But, recently I found out that my web stops working. The part that is broken is when placing a gif image. Image(gif,w,h); When comments it out, everything work the same.

**Comment by n1ckfg** [comment]
Same here--any clues much appreciated; this was a fun library to use in class.

**Comment by brilovescoding** [comment]
The applicable error message:

> Uncaught DOMException: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The image argument is a canvas element with a width or height of 0.

**Comment by WillGeller** [comment]
Ya this sounded really cool, it would be great if someone could get it working on the latest version of P5 / openprocessing
